#!/bin/sh
# Script pour passer un site apache en ssl
# crée par Anthony le 01/04/2019 derniere modification par Anthony le 20/10/2021
#
# Crée un nouveau vhost apache en 443 et modifie celui en 80 avec redirection
#
# usage : cree-ssl-site-apache nomdossier nomsiteweb
# Exemple : cree-ssl-site-apache dossier-site exemple.com
#

# Variables
nb_args=2
chemin_apache_available=/etc/apache2/sites-available
chemin_apache_enabled=/etc/apache2/sites-enabled

# Début du script
if [ "$#" -ne $nb_args ];
    then
        echo "Vous devez saisir $nb_args argument(s) et vous en avez saisi $# ..."
        echo La syntaxe est : cree-ssl--apache nomdossier nomsiteweb
	echo Exemple : cree-ssl-site-apache dossier-site exemple.com
        exit 1
    else

# Fabrication du fichier de conf apache dans sites-available
# 1 copie du fichier vhost 80 pouyr le passer en 443
                cp -prv $chemin_apache_available/$1.conf $chemin_apache_available/$1-ssl.conf
#               cp -prv $chemin_apache_available/default-ssl.conf $chemin_apache_available/ssl.$2.conf

# 2 modif conf du fichier 443
                sed -i -e "s/:80/:443/g" $chemin_apache_available/$1-ssl.conf
        	sed -i "/<VirtualHost */i\<IfModule mod_ssl.c>" $chemin_apache_available/$1-ssl.conf
		sed -i "/VirtualHost>/a\</IfModule>" $chemin_apache_available/$1-ssl.conf
		sed -i "/combined/a SSLCertificateFile /etc/letsencrypt/live/$2/fullchain.pem" $chemin_apache_available/$1-ssl.conf
		sed -i "/SSLCertificateFile/a SSLCertificateKeyFile /etc/letsencrypt/live/$2/privkey.pem" $chemin_apache_available/$1-ssl.conf
		sed -i "/SSLCertificateKeyFile/a Include /etc/letsencrypt/options-ssl-apache.conf" $chemin_apache_available/$1-ssl.conf
#               sed -i -e "s/chaine1/chaine2/g" $chemin_apache_available/ssl.$1.conf
#
# 3 modif conf du fichier 80
		sed -i "/combined/a RewriteEngine on" $chemin_apache_available/$1.conf
		sed -i "/RewriteEngine on/a RewriteCond %{SERVER_NAME} =$2" $chemin_apache_available/$1.conf
		sed -i "/RewriteCond/a RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]" $chemin_apache_available/$1.conf
#
# 4 lancement certbot
		certbot certonly --apache
#
# 5 creation du lien symbolique dans sites-enabled
                ln -sfn $chemin_apache_available/$1-ssl.conf $chemin_apache_enabled/$1-ssl.conf
# 6 reload config apache
                apache2ctl graceful
                exit 0
# 4 todo lancer certbot

fi

