#!/bin/sh
# Script d'initialisation pour un nouveau serveur EPSILOG
# cree par Anthony le 22/12/2014
# derniere modification par Anthony le 20/10/2021
#
#usage : init_serveur_epsilog
#
# Variables

usr_epsilog=epsimin
chemin_www=/var/www
groupapache=www-data
groupepsilog=epsilog

# Installations de paquets
# fail2ban
# automatisation maj debian
# certbot / letsencrypt
# snmp ?? centreon ??

-	apt-get update
-	apt-get upgrade
-	apt-get install open-vm-tools
-	apt-get install proftpd
-	apt-get install fail2ban
-	reconfigurer le fichier /etc/network/interfaces
apt-get install apache2
apt-get install mysql-server
mysql_secure_installation
apt-get install php5 php-pear php5-mysql
service apache2 restart

gestion envoiexe de michel

-	apt-get install awstats
-	a2enmod 

rsync pour copie de fichiers entre serveurs




# Récupérations de config types EPSILOG
# fail2ban
# proftpd

# ajout de l'utilisateur destination au groupe EPSILOG
usermod –G $groupepsilog $usr_serveur_destination

# récupération de la config de proftpd et redémarrage du service
cp /etc/proftpd/proftpd.conf /etc/proftpd/proftpd.conf.origine
cp /etc/proftpd/proftpd.conf /home/epsimin/sauve/proftp.conf.origine
scp -pv $usr_serveur_source@$adr_serveur_source:/etc/proftpd/proftpd.conf /etc/proftpd
/etc/init.d/proftpd restart

# récupération de la config de apache2 et redémarrage du service
cp /etc/apache2/sites-enabled/000-default /home/epsimin/sauve/000-default.origine
scp -pv $usr_serveur_source@$adr_serveur_source:/etc/apache2/sites-enabled/000-default /etc/apache2/sites-enabled
/etc/init.d/apache2 restart
